# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43b1d261106817f20813cf7b1589c0985401f529d802d7eb0599137d97a02b22a8dd46d3d64581dbd93bfe6b0f95bce76db7f2b2562ac17c8896551ff3078bc1

test:
  secret_key_base: 9912fdc1afba14f557636ecee1aaaeb14a2b900c752831463b5a9cb335f67551742abb6db911a1c278548259737aca006266cb07064b33cb91863df7ab5cf8cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
